name: Push Changes to Pages
on: push
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - name: clone pages repo
        run: |
          git clone https://github.com/MrPowerGamerBR/GitHubPageTestReceiver.git
      - name: going into the directory
        run: |
          cd GitHubPageTestReceiver
      - name: view files
        run: |
          ls
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: write something
        run: |
          "owo whats this" > test
      - name: commit
        run: |
          git add test
          git commit -m "test commit"
          git push origin master